name: Jellyseer Release

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-pgsql'

jobs:
  semantic-release:
    name: Tag and release latest version
    runs-on: ubuntu-20.04
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/jellyseerr-pgsql:v1.7.0
